In [1]:
!pip install snowflake-connector-python

Requirement already satisfied: snowflake-connector-python in c:\users\azwandesktop\onedrive\personal data projects\1-virtualenv\python311env\lib\site-packages (3.10.1)
Requirement already satisfied: asn1crypto<2.0.0,>0.24.0 in c:\users\azwandesktop\onedrive\personal data projects\1-virtualenv\python311env\lib\site-packages (from snowflake-connector-python) (1.5.1)
Requirement already satisfied: cffi<2.0.0,>=1.9 in c:\users\azwandesktop\onedrive\personal data projects\1-virtualenv\python311env\lib\site-packages (from snowflake-connector-python) (1.15.1)
Requirement already satisfied: cryptography<43.0.0,>=3.1.0 in c:\users\azwandesktop\onedrive\personal data projects\1-virtualenv\python311env\lib\site-packages (from snowflake-connector-python) (41.0.1)
Requirement already satisfied: pyOpenSSL<25.0.0,>=16.2.0 in c:\users\azwandesktop\onedrive\personal data projects\1-virtualenv\python311env\lib\site-packages (from snowflake-connector-python) (23.2.0)
Requirement already satisfied: pyjwt<3.0.0 in c:\users\azwandesktop\onedrive\personal data projects\1-virtualenv\python311env\lib\site-packages (from snowflake-connector-python) (2.7.0)
Requirement already satisfied: pytz in c:\users\azwandesktop\onedrive\personal data projects\1-virtualenv\python311env\lib\site-packages (from snowflake-connector-python) (2023.3)
Requirement already satisfied: requests<3.0.0 in c:\users\azwandesktop\onedrive\personal data projects\1-virtualenv\python311env\lib\site-packages (from snowflake-connector-python) (2.31.0)
Requirement already satisfied: packaging in c:\users\azwandesktop\onedrive\personal data projects\1-virtualenv\python311env\lib\site-packages (from snowflake-connector-python) (23.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\azwandesktop\onedrive\personal data projects\1-virtualenv\python311env\lib\site-packages (from snowflake-connector-python) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\azwandesktop\onedrive\personal data projects\1-virtualenv\python311env\lib\site-packages (from snowflake-connector-python) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\azwandesktop\onedrive\personal data projects\1-virtualenv\python311env\lib\site-packages (from snowflake-connector-python) (2023.5.7)
Requirement already satisfied: typing-extensions<5,>=4.3 in c:\users\azwandesktop\onedrive\personal data projects\1-virtualenv\python311env\lib\site-packages (from snowflake-connector-python) (4.7.1)
Requirement already satisfied: filelock<4,>=3.5 in c:\users\azwandesktop\onedrive\personal data projects\1-virtualenv\python311env\lib\site-packages (from snowflake-connector-python) (3.12.2)
Requirement already satisfied: sortedcontainers>=2.4.0 in c:\users\azwandesktop\onedrive\personal data projects\1-virtualenv\python311env\lib\site-packages (from snowflake-connector-python) (2.4.0)
Requirement already satisfied: platformdirs<5.0.0,>=2.6.0 in c:\users\azwandesktop\onedrive\personal data projects\1-virtualenv\python311env\lib\site-packages (from snowflake-connector-python) (3.11.0)
Requirement already satisfied: tomlkit in c:\users\azwandesktop\onedrive\personal data projects\1-virtualenv\python311env\lib\site-packages (from snowflake-connector-python) (0.11.8)
Requirement already satisfied: pycparser in c:\users\azwandesktop\onedrive\personal data projects\1-virtualenv\python311env\lib\site-packages (from cffi<2.0.0,>=1.9->snowflake-connector-python) (2.21)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\azwandesktop\onedrive\personal data projects\1-virtualenv\python311env\lib\site-packages (from requests<3.0.0->snowflake-connector-python) (1.26.18)

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import snowflake.connector

In [3]:
ACCOUNT = 'UFIJDLY-NF47757'
# PASSWORD = 
# WAREHOUSE = ''

In [4]:
ctx = snowflake.connector.connect(user='azwan92',
                            password='Akenapa92!',
                            account=ACCOUNT,
                            warehouse='COMPUTE_WH',
                            database='COFFEE',
                            schema='RAW',
                            role='ACCOUNTADMIN')

In [5]:
ctx.execute_string

In [6]:
# a = ctx.execute_string("SELECT * FROM COFFEE.raw.fact_sales limit 100",)

In [7]:
a = ctx.cursor().execute("SELECT * FROM COFFEE.raw.fact_sales limit 100")

In [8]:
a.fetch_pandas_all()

,TRANSACTION_ID,TRANSACTION_DATE,TRANSACTION_TIME,TRANSACTION_QTY,STORE_ID,STORE_LOCATION,PRODUCT_ID,UNIT_PRICE,PRODUCT_CATEGORY,PRODUCT_TYPE,PRODUCT_DETAIL
0,1,1672531200000000,07:06:11,2,5,Lower Manhattan,32,3.00,Coffee,Gourmet brewed coffee,Ethiopia Rg
1,2,1672531200000000,07:08:56,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
2,3,1672531200000000,07:14:04,2,5,Lower Manhattan,59,4.50,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
3,4,1672531200000000,07:20:24,1,5,Lower Manhattan,22,2.00,Coffee,Drip coffee,Our Old Time Diner Blend Sm
4,5,1672531200000000,07:22:41,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
...,...,...,...,...,...,...,...,...,...,...,...
95,96,1672531200000000,10:35:47,1,8,Hell's Kitchen,60,3.75,Drinking Chocolate,Hot chocolate,Sustainably Grown Organic Rg
96,97,1672531200000000,10:41:53,1,5,Lower Manhattan,59,4.50,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
97,98,1672531200000000,10:47:53,2,5,Lower Manhattan,36,3.75,Coffee,Premium brewed coffee,Jamaican Coffee River Lg
98,99,1672531200000000,10:49:13,2,8,Hell's Kitchen,51,3.00,Tea,Brewed Black tea,Earl Grey Lg
99,100,1672531200000000,10:49:51,2,5,Lower Manhattan,61,4.75,Drinking Chocolate,Hot chocolate,Sustainably Grown Organic Lg

In [ ]:
# https://docs.snowflake.com/en/developer-guide/python-connector/python-connector-api#write_pandas
# https://www.youtube.com/watch?v=OLXkGB7krGo